[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "DpuoBu7yYFNcMXNxKWD8J8a38uzR9VNE0TE2FkYIoVU="

[auth.default]
client_id = "wxy74RrvpXtTdDIjJq5RM4Lpz3TpSBR2"
client_secret = "A_h0k83Zyly0wXc2VtTh-BU2nceVFwRrBGMhGk9Qvg6AASVNKefb_-s1hu-nPI9J"
server_metadata_url = "https://tsar.eu.auth0.com/.well-known/openid-configuration"
